INSERT INTO Pizza ([Name]) VALUES ('Margherita')
INSERT INTO Pizza ([Name]) VALUES ('Pepperoni')
INSERT INTO Pizza ([Name]) VALUES ('Roma')
INSERT INTO Pizza ([Name]) VALUES ('Napoli')
INSERT INTO Pizza ([Name]) VALUES ('Prosciutto')
INSERT INTO Pizza ([Name]) VALUES ('Végétarienne')
INSERT INTO Pizza ([Name]) VALUES ('Calzone')
INSERT INTO Pizza ([Name]) VALUES ('Quatre fromages')
INSERT INTO Pizza ([Name]) VALUES ('Hawaï')
INSERT INTO Pizza ([Name]) VALUES ('Bolognaise')
INSERT INTO Pizza ([Name]) VALUES ('Sicilienne')